### ISSUE TITLE
[question] GlusterFs persistent volume 

### ISSUE THREAD

**Issue by pditommaso** [kubenow/KubeNow#243]
When configuring the GlusterFS storage is KubeNow able to setup the Persistent Volume in the Kubernetes cluster?

**Comment by andersla** [comment]
It will create a Gluster Kubernetes StorageClass that will be the default storage class in the cluster and will automatically give the asked for storage to a Persistent Volume Claim.

**Comment by mcapuccini** [comment]
Yes, all you need to do is to create a PersistentVolumeClaim, the PersistentVolume should be provisioned automatically by Heketi. You can give a look to the [persistent volume test](https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/shared-volume-test/tasks/main.yml) for an example.

**Comment by pditommaso** [comment]
Being so it's enough that I add a volume claim like the one below? 

```
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: test-claim
      restartPolicy: Never
```

and if so what's the claimName to be used? or do I need to create a `PersistentVolumeClaim` before launching the pod/job ?
