### ISSUE TITLE
Empty /etc/default/docker causes build error with some source images

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#32]
Empty /etc/default/docker causes build error with some source images:

```
all: Errors were encountered while processing:
all: docker-engine
```

caused by

```
all: Setting up docker-engine (1.12.3-0~xenial) ...
    all:
    all: Configuration file '/etc/default/docker'
    all: ==> File on system created by you or by a script.
    all: ==> File also in package provided by package maintainer.
    all: What would you like to do about it ?  Your options are:
    all: Y or I  : install the package maintainer's version
    all: N or O  : keep your currently-installed version
    all: D     : show the differences between the versions
    all: Z     : start a shell to examine the situation
    all: The default action is to keep your current version.
    all: *** docker (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package docker-engine (--configure):
    all: end of file on stdin at conffile prompt
    all: Setting up ebtables (2.0.10.4-3.4ubuntu1) ...
```
